# Site settings
title: vsSolutionBuildEvent
subtitle: Flexible actions for all  ...
email: entry.reg@gmail.com
baseurl: ""
url: "http://vssbe.r-eg.net" # base hostname

# root path to doc structure
docp: "./doc"
#permalink: pretty

collections:
    doc: # main documentation
        output: true


# Build settings
markdown: kramdown
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
  
highlighter: pygments

# Data
changelog: "https://bitbucket.org/3F/vssolutionbuildevent/raw/master/changelog.txt"
vsixVersions: [v0.11.4, v0.11.3, v0.11.2, v0.11]
vsixVersionsOlder: [v0.10.1, v0.9]