# Site settings
title: vsSolutionBuildEvent
subtitle: Flexible actions for all  ...
email: entry.reg@gmail.com
baseurl: ""
url: "http://vssbe.r-eg.net" # base hostname

# root path to doc structure
docp: "/doc"
#permalink: pretty

collections:
    doc: # main documentation
        output: true


# Build settings
markdown: kramdown

redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "space_after_headers", "footnotes", "prettify"]

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
    auto_ids: true # generate ID for headings
    input: GFM # +GitHub Flavored Markdown
  
#highlighter: pygments
highlighter: rouge

# suitable langs with rouge as the SBE-Scripts
sbelang: clojure
sbelang1: java
sbelang2: tcl
sbelang3: ocaml

# suitable langs with rouge as the MSBuild properties and Property Functions
msblang: bash


#######################################
# Latest binaries
##############

# Downloads
         # Specifies variables with prefix:
            # 'lnkCur_' - Actual or recommended version. /Format: [ "short name", "full name", "link" ]
            # 'lnkList_' - List of all previous versions. /Format: [ [ "version or short name", "full name", "link" ], ... ]
            # 'lnkOld_' - List of all deprecated versions. /Format: [ [ "version or short name", "full name", "link" ], ... ]
            # 'lnkAll_' - Link to browsing all available versions. /Format: [ "name", "link" ]


## VSPackage

lnkCur_VSPackage:   [ "v0.12.8", "vsSolutionBuildEvent_v0.12.8.4975_[50e9a29][net40].vsix", "https://visualstudiogallery.msdn.microsoft.com/0d1dbfd7-ed8a-40af-ae39-281bfeca2334/referral/118151" ]
lnkList_VSPackage:  [
                        [ "v0.12.8_net40", "vsSolutionBuildEvent_v0.12.8.4975_[50e9a29][net40].vsix", "https://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.12.8.4975_%5B50e9a29%5D%5Bnet40%5D.vsix/download" ],
                        [ "v0.12.8_net45", "vsSolutionBuildEvent_v0.12.8.4976_[50e9a29][net45].vsix", "https://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.12.8.4976_%5B50e9a29%5D%5Bnet45%5D.vsix/download" ],
                        [ "v0.12.7", "vsSolutionBuildEvent_v0.12.7.3805_[48df3db][net40].vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.12.7.3805_%5B48df3db%5D%5Bnet40%5D.vsix/download" ]
                    ]
lnkOld_VSPackage:   [
                        [ "v0.12.6", "vsSolutionBuildEvent_v0.12.6.5177_[6ad0511][net40].vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.12.6.5177_%5B6ad0511%5D%5Bnet40%5D.vsix/download" ],
                        [ "v0.12.5", "vsSolutionBuildEvent_v0.12.5.2477_[d018ea4][net40].vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.12.5.2477_%5Bd018ea4%5D%5Bnet40%5D.vsix/download" ],
                        [ "v0.12.4", "vsSolutionBuildEvent_v0.12.4.4187_[f8e9259][net40].vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.12.4.4187_%5Bf8e9259%5D%5Bnet40%5D.vsix/download" ],
                        [ "v0.12.3", "vsSolutionBuildEvent_v0.12.3.vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.12.3.vsix/download" ],
                        [ "v0.11.4", "vsSolutionBuildEvent_v0.11.4.vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.11.4.vsix/download" ]
                    ]
lnkAll_VSPackage:   [ "/v0.x/", "http://sourceforge.net/projects/vssbe/files/v0.x/" ]

## CI.MSBuild

lnkCur_CIMSBuild:   [ "v1.6", "CI.MSBuild_v1.6_[48df3db][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/CI.MSBuild_v1.6_%5B48df3db%5D%5Bnet40%5D.zip/download" ]
lnkList_CIMSBuild:  [ 
                        [ "v1.6", "CI.MSBuild_v1.6_[48df3db][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/CI.MSBuild_v1.6_%5B48df3db%5D%5Bnet40%5D.zip/download" ],
                        [ "v1.5", "CI.MSBuild_v1.5_[8bde22a][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/CI.MSBuild_v1.5_%5B8bde22a%5D%5Bnet40%5D.zip/download" ]
                    ]                
lnkOld_CIMSBuild:   [ 
                        [ "v1.4", "CI.MSBuild_v1.4_[1e67da9][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/CI.MSBuild_v1.4_%5B1e67da9%5D%5Bnet40%5D.zip/download" ],
                        [ "v1.3", "CI.MSBuild_v1.3_[120ea89][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/CI.MSBuild_v1.3_%5B120ea89%5D%5Bnet40%5D.zip/download" ]
                    ]
lnkAll_CIMSBuild:   [ "/CI-Utilities/CI.MSBuild/", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/"]

## Devenv

lnkCur_Devenv:  [ "v1.3", "Devenv_v1.3_[e3b9d87][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/Devenv/Devenv_v1.3_%5Be3b9d87%5D%5Bnet40%5D.zip/download" ]
lnkList_Devenv: [
                    [ "v1.3", "Devenv_v1.3_[e3b9d87][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/Devenv/Devenv_v1.3_%5Be3b9d87%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.2", "Devenv_v1.2_[f9bf5fc][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/Devenv/Devenv_v1.2_%5Bf9bf5fc%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.1", "Devenv_v1.1_[e9ad3bd][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/Devenv/Devenv_v1.1_%5Be9ad3bd%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.0", "Devenv_v1.0_[5d7aa0c].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/Devenv/Devenv_v1.0_%5B5d7aa0c%5D.zip/download" ]
                ]
lnkOld_Devenv:  []
lnkAll_Devenv:  [ "/CI-Utilities/Devenv/", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/Devenv/" ]


## API

lnkCur_API:     [ "v1.4", "Bridge_v1.4_[50e9a29][net40].zip", "https://sourceforge.net/projects/vssbe/files/API/Bridge/Bridge_v1.4_%5B50e9a29%5D%5Bnet40%5D.zip/download" ]
lnkList_API:    [
                    [ "v1.4", "Bridge_v1.4_[50e9a29][net40].zip", "https://sourceforge.net/projects/vssbe/files/API/Bridge/Bridge_v1.4_%5B50e9a29%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.3", "Bridge_v1.3_[8bde22a][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Bridge/Bridge_v1.3_%5B8bde22a%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.2", "Bridge_v1.2_[dc72d4c][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Bridge/Bridge_v1.2_%5Bdc72d4c%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.1", "Bridge_v1.1_[e9ad3bd][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Bridge/Bridge_v1.1_%5Be9ad3bd%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.0", "Bridge_v1.0_[5d7aa0c].zip", "http://sourceforge.net/projects/vssbe/files/API/Bridge/Bridge_v1.0_%5B5d7aa0c%5D.zip/download" ]
                ]
lnkOld_API:     []
lnkAll_API:     [ "/API/Bridge/", "http://sourceforge.net/projects/vssbe/files/API/Bridge/" ]

## Provider

lnkCur_Provider:    [ "v3.0", "Provider_v3.0_[8bde22a][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Provider/Provider_v3.0_%5B8bde22a%5D%5Bnet40%5D.zip/download" ]
lnkList_Provider:   [
                        [ "v3.0", "Provider_v3.0_[8bde22a][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Provider/Provider_v3.0_%5B8bde22a%5D%5Bnet40%5D.zip/download" ]
                    ]
lnkOld_Provider:    [
                        [ "v2.1", "Provider_v2.1_[f9bf5fc][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Provider/Provider_v2.1_%5Bf9bf5fc%5D%5Bnet40%5D.zip/download" ],
                        [ "v2.0", "Provider_v2.0_[e9ad3bd][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Provider/Provider_v2.0_%5Be9ad3bd%5D%5Bnet40%5D.zip/download" ],
                        [ "v1.0", "Provider_v1.0_[5d7aa0c].zip", "http://sourceforge.net/projects/vssbe/files/API/Provider/Provider_v1.0_%5B5d7aa0c%5D.zip/download" ]
                    ]
lnkAll_Provider:    [ "/API/Provider/", "http://sourceforge.net/projects/vssbe/files/API/Provider/" ]


## NuGet Package for CI

lnkCur_CIMNuGet:    [ "v1.6.1208", "vsSBE.CI.MSBuild.1.6.1208_net40.nupkg", "https://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.6.1208_net40.nupkg/download" ]
lnkList_CIMNuGet:   [
                        [ "v1.6.1208_net40", "vsSBE.CI.MSBuild.1.6.1208_net40.nupkg", "https://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.6.1208_net40.nupkg/download" ],
                        [ "v1.6.1208_net45", "vsSBE.CI.MSBuild.1.6.1208_net45.nupkg", "https://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.6.1208_net45.nupkg/download" ],
                        [ "v1.6.1207", "vsSBE.CI.MSBuild.1.6.1207.nupkg", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.6.1207.nupkg/download" ],
                        [ "v1.5.1206", "vsSBE.CI.MSBuild.1.5.1206.nupkg", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.5.1206.nupkg/download" ],
                        [ "v1.5.1", "vsSBE.CI.MSBuild.1.5.1.nupkg", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.5.1.nupkg/download" ]
                    ]
lnkOld_CIMNuGet:    [
                        [ "v1.5.0", "vsSBE.CI.MSBuild.1.5.0.nupkg", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.5.0.nupkg/download" ],
                        [ "v1.4.0", "vsSBE.CI.MSBuild.1.4.0.nupkg", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.4.0.nupkg/download" ],
                        [ "v1.3.0", "vsSBE.CI.MSBuild.1.3.0.nupkg", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.3.0.nupkg/download" ]
                    ]
lnkAll_CIMNuGet:    [ "/CI-Utilities/CI.MSBuild/NuGet_packages/", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/" ]


## ClientDemo

lnkCur_ClientDemo:  [ "[e3b9d87][net45]&#40;4989&#41;", "ClientDemo_[e3b9d87][net45]&#40;4989&#41;.zip", "http://sourceforge.net/projects/vssbe/files/dev/clients/client.vssbe.dll/ClientDemo_%5Be3b9d87%5D%5Bnet45%5D%284989%29.zip/download" ]
lnkList_ClientDemo: [
                        [ "[e3b9d87][net45]&#40;4989&#41;", "ClientDemo_[e3b9d87][net45]&#40;4989&#41;.zip", "http://sourceforge.net/projects/vssbe/files/dev/clients/client.vssbe.dll/ClientDemo_%5Be3b9d87%5D%5Bnet45%5D%284989%29.zip/download" ],
                        [ "[8bde22a][net40]&#40;2692&#41;", "ClientDemo_[8bde22a][net40]&#40;2692&#41;.zip", "http://sourceforge.net/projects/vssbe/files/dev/clients/client.vssbe.dll/ClientDemo_%5B8bde22a%5D%5Bnet40%5D%282692%29.zip/download" ]
                    ]
lnkOld_ClientDemo:  []
lnkAll_ClientDemo:  [ "/dev/clients/client.vssbe.dll/", "https://sourceforge.net/projects/vssbe/files/dev/clients/client.vssbe.dll/" ]

## get.CIM.bat

lnkCur_getCIM:  [ "get.CIM.bat", "get.CIM.bat", "http://vssbe.r-eg.net/doc/CI/get.CIM.bat" ]

#######################################
# Sources
##############

# Web

lnkVSGallery: "http://visualstudiogallery.msdn.microsoft.com/0d1dbfd7-ed8a-40af-ae39-281bfeca2334/"
lnkVSGallery_vsCE: ""

# Dev

lnkBackupLib: [ "/dev/lib/", "http://sourceforge.net/projects/vssbe/files/dev/lib/"]
lnkBackupSrc: [ "/dev/sources/", "https://sourceforge.net/projects/vssbe/files/dev/sources/" ]

lnkSrcClientDemo: [ "ClientDemo", "https://github.com/3F/vsSolutionBuildEvent/tree/master/ClientDemo" ]


# other

changelog: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/changelog.txt"
changelogCIM: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/CI.MSBuild/changelog.txt"
changelogDevenv: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Devenv/changelog.txt"
changelogAPI: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Bridge/changelog.txt"
changelogProvider: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Provider/changelog.txt"

readme: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/README.md"
license: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/LICENSE"

versionVsix: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/.version"
versionCIM: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/CI.MSBuild/.version"
versionDevenv: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Devenv/.version"
versionAPI: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Bridge/.version"
versionProvider: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Provider/.version"

sfstat: "https://sourceforge.net/projects/vssbe/files/stats/json?start_date=2013-11-20&end_date=2222-01-01"

#######################################
# Services
##############

editPagePath: "https://github.com/3F/web.vsSBE/edit/gh-pages/"