# Site settings
title: vsSolutionBuildEvent
subtitle: Flexible actions for all  ...
email: entry.reg@gmail.com
baseurl: ""
url: "http://vssbe.r-eg.net" # base hostname

# root path to doc structure
docp: "/doc"
#permalink: pretty

collections:
    doc: # main documentation
        output: true


# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
    auto_ids: true # generate ID for headings
    input: GFM # +GitHub Flavored Markdown
  
highlighter: pygments


#######################################
# Latest binaries
##############

# Downloads
         # Specifies variables with prefix:
            # 'lnkCur_' - Actual or recommended version. /Format: [ "short name", "full name", "link" ]
            # 'lnkList_' - List of all previous versions. /Format: [ [ "version or short name", "full name", "link" ], ... ]
            # 'lnkOld_' - List of all deprecated versions. /Format: [ [ "version or short name", "full name", "link" ], ... ]
            # 'lnkAll_' - Link to browsing all available versions. /Format: [ "name", "link" ]


## VSPackage

lnkCur_VSPackage:   [ "v0.12.4", "vsSolutionBuildEvent_v0.12.4.4187_[f8e9259][net40].vsix", "http://visualstudiogallery.msdn.microsoft.com/0d1dbfd7-ed8a-40af-ae39-281bfeca2334/referral/118151" ]
lnkList_VSPackage:  [
                        [ "v0.12.4", "vsSolutionBuildEvent_v0.12.4.4187_[f8e9259][net40].vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.12.4.4187_%5Bf8e9259%5D%5Bnet40%5D.vsix/download" ],
                        [ "v0.12.3", "vsSolutionBuildEvent_v0.12.3.vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.12.3.vsix/download" ],
                        [ "v0.12.2", "vsSolutionBuildEvent_v0.12.2.vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.12.2.vsix/download" ]
                    ]
lnkOld_VSPackage:   [
                        [ "v0.12.1", "vsSolutionBuildEvent_v0.12.1.vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.12.1.vsix/download" ],
                        [ "v0.11.4", "vsSolutionBuildEvent_v0.11.4.vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.11.4.vsix/download" ],
                        [ "v0.10.1", "vsSolutionBuildEvent_v0.10.1.vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.10.1.vsix/download" ],
                        [ "v0.9", "vsSolutionBuildEvent_v0.9.vsix", "http://sourceforge.net/projects/vssbe/files/v0.x/vsSolutionBuildEvent_v0.9.vsix/download" ]
                    ]
lnkAll_VSPackage:   [ "/v0.x/", "http://sourceforge.net/projects/vssbe/files/v0.x/" ]

## CI.MSBuild

lnkCur_CIMSBuild:   [ "v1.5", "CI.MSBuild_v1.5_[8bde22a][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/CI.MSBuild_v1.5_%5B8bde22a%5D%5Bnet40%5D.zip/download" ]
lnkList_CIMSBuild:  [ 
                        [ "v1.5", "CI.MSBuild_v1.5_[8bde22a][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/CI.MSBuild_v1.5_%5B8bde22a%5D%5Bnet40%5D.zip/download" ]
                    ]                
lnkOld_CIMSBuild:   [ 
                        [ "v1.4", "CI.MSBuild_v1.4_[1e67da9][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/CI.MSBuild_v1.4_%5B1e67da9%5D%5Bnet40%5D.zip/download" ],
                        [ "v1.3", "CI.MSBuild_v1.3_[120ea89][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/CI.MSBuild_v1.3_%5B120ea89%5D%5Bnet40%5D.zip/download" ]
                    ]
lnkAll_CIMSBuild:   [ "/CI-Utilities/CI.MSBuild/", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/"]

## Devenv

lnkCur_Devenv:  [ "v1.2", "Devenv_v1.2_[f9bf5fc][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/Devenv/Devenv_v1.2_%5Bf9bf5fc%5D%5Bnet40%5D.zip/download" ]
lnkList_Devenv: [
                    [ "v1.2", "Devenv_v1.2_[f9bf5fc][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/Devenv/Devenv_v1.2_%5Bf9bf5fc%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.1", "Devenv_v1.1_[e9ad3bd][net40].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/Devenv/Devenv_v1.1_%5Be9ad3bd%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.0", "Devenv_v1.0_[5d7aa0c].zip", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/Devenv/Devenv_v1.0_%5B5d7aa0c%5D.zip/download" ]
                ]
lnkOld_Devenv:  []
lnkAll_Devenv:  [ "/CI-Utilities/Devenv/", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/Devenv/" ]


## API

lnkCur_API:     [ "v1.3", "Bridge_v1.3_[8bde22a][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Bridge/Bridge_v1.3_%5B8bde22a%5D%5Bnet40%5D.zip/download" ]
lnkList_API:    [
                    [ "v1.3", "Bridge_v1.3_[8bde22a][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Bridge/Bridge_v1.3_%5B8bde22a%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.2", "Bridge_v1.2_[dc72d4c][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Bridge/Bridge_v1.2_%5Bdc72d4c%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.1", "Bridge_v1.1_[e9ad3bd][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Bridge/Bridge_v1.1_%5Be9ad3bd%5D%5Bnet40%5D.zip/download" ],
                    [ "v1.0", "Bridge_v1.0_[5d7aa0c].zip", "http://sourceforge.net/projects/vssbe/files/API/Bridge/Bridge_v1.0_%5B5d7aa0c%5D.zip/download" ]
                ]
lnkOld_API:     []
lnkAll_API:     [ "/API/Bridge/", "http://sourceforge.net/projects/vssbe/files/API/Bridge/" ]

## Provider

lnkCur_Provider:    [ "v3.0", "Provider_v3.0_[8bde22a][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Provider/Provider_v3.0_%5B8bde22a%5D%5Bnet40%5D.zip/download" ]
lnkList_Provider:   [
                        [ "v3.0", "Provider_v3.0_[8bde22a][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Provider/Provider_v3.0_%5B8bde22a%5D%5Bnet40%5D.zip/download" ]
                    ]
lnkOld_Provider:    [
                        [ "v2.1", "Provider_v2.1_[f9bf5fc][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Provider/Provider_v2.1_%5Bf9bf5fc%5D%5Bnet40%5D.zip/download" ],
                        [ "v2.0", "Provider_v2.0_[e9ad3bd][net40].zip", "http://sourceforge.net/projects/vssbe/files/API/Provider/Provider_v2.0_%5Be9ad3bd%5D%5Bnet40%5D.zip/download" ],
                        [ "v1.0", "Provider_v1.0_[5d7aa0c].zip", "http://sourceforge.net/projects/vssbe/files/API/Provider/Provider_v1.0_%5B5d7aa0c%5D.zip/download" ]
                    ]
lnkAll_Provider:    [ "/API/Provider/", "http://sourceforge.net/projects/vssbe/files/API/Provider/" ]


## NuGet Package for CI

lnkCur_CIMNuGet:    [ "v1.5.0", "vsSBE.CI.MSBuild.1.5.0.nupkg", "https://www.nuget.org/api/v2/package/vsSBE.CI.MSBuild/" ]
lnkList_CIMNuGet:   [
                        [ "v1.5.0", "vsSBE.CI.MSBuild.1.5.0.nupkg", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.5.0.nupkg/download" ],
                        [ "v1.4.0", "vsSBE.CI.MSBuild.1.4.0.nupkg", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.4.0.nupkg/download" ]
                    ]
lnkOld_CIMNuGet:    [
                        [ "v1.3.0", "vsSBE.CI.MSBuild.1.3.0.nupkg", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/vsSBE.CI.MSBuild.1.3.0.nupkg/download" ],
                        [ "v1.2.1", "vsSBE.CI.MSBuild.1.2.1.nupkg", "https://www.nuget.org/api/v2/package/vsSBE.CI.MSBuild/1.2.1" ]
                    ]
lnkAll_CIMNuGet:    [ "/CI-Utilities/CI.MSBuild/NuGet_packages/", "http://sourceforge.net/projects/vssbe/files/CI-Utilities/CI.MSBuild/NuGet_packages/" ]


## ClientDemo

lnkCur_ClientDemo:  [ "[8bde22a][net40]&#40;2692&#41;", "ClientDemo_[8bde22a][net40]&#40;2692&#41;.zip", "http://sourceforge.net/projects/vssbe/files/dev/clients/client.vssbe.dll/ClientDemo_%5B8bde22a%5D%5Bnet40%5D%282692%29.zip/download" ]
lnkList_ClientDemo: [
                        [ "[8bde22a][net40]&#40;2692&#41;", "ClientDemo_[8bde22a][net40]&#40;2692&#41;.zip", "http://sourceforge.net/projects/vssbe/files/dev/clients/client.vssbe.dll/ClientDemo_%5B8bde22a%5D%5Bnet40%5D%282692%29.zip/download" ]
                    ]
lnkOld_ClientDemo:  []
lnkAll_ClientDemo:  [ "/dev/clients/client.vssbe.dll/", "https://sourceforge.net/projects/vssbe/files/dev/clients/client.vssbe.dll/" ]


#######################################
# Sources
##############

# Web

lnkVSGallery: "http://visualstudiogallery.msdn.microsoft.com/0d1dbfd7-ed8a-40af-ae39-281bfeca2334/"
lnkVSGallery_vsCE: ""

# Dev

lnkBackupLib: [ "/dev/lib/", "http://sourceforge.net/projects/vssbe/files/dev/lib/"]
lnkBackupSrc: [ "/dev/sources/", "https://sourceforge.net/projects/vssbe/files/dev/sources/" ]


# other

changelog: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/changelog.txt"
changelogCIM: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/CI.MSBuild/changelog.txt"
changelogDevenv: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Devenv/changelog.txt"
changelogAPI: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Bridge/changelog.txt"
changelogProvider: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Provider/changelog.txt"

readme: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/README.md"
license: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/LICENSE"

versionVsix: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/.version"
versionCIM: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/CI.MSBuild/.version"
versionDevenv: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Devenv/.version"
versionAPI: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Bridge/.version"
versionProvider: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/Provider/.version"
